### ISSUE TITLE
Typos in index.html

### ISSUE THREAD

**Issue by SelfMadeSystem** [CodeSearchBot/CodeSearch#1]
You wrote "CodeSeach" instead of "CodeSearch" 19 times in index.html. You also wrote "CodeSeah" once in the demo space. (source: Ctrl + F)

**Comment by SelfMadeSystem** [comment]
I write "type" instead of "typo" so often bruh ngl. prolly bc I use typescript but idk

**Comment by SilkePilon** [comment]
xD

**Comment by SilkePilon** [comment]
shut be fixed rn
